on:
  pull_request:
    types: [opened]
  workflow_dispatch:
    inputs:
      version:
        description: "version"
        required: true
    
jobs:
  thank-user:
    runs-on: ubuntu-20.04
    name: Say thanks for the PR
    steps:
      - name: echo var
        if: github.event.inputs.version == '' || github.event.inputs.version == 22
        run: |
          echo ${{ github.event.inputs.version }}
