on:
  pull_request:
    types: [opened]
    
jobs:
  deploy-preview:
    runs-on: ubuntu-20.04
    name: Deploy preview
    steps:
      - name: Notify about starting this deployment 
        uses: imperfect-fourth/comment-progress@enums
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'imperfect-fourth/test'
          number: ${{ github.event.number }}
          id: deploy-preview
          message: 'Starting deployment of this pull request.'

      - name: Deploy preview
        run: |
          echo "deploy preview"
          sleep 30

      - name: Notify about the result of this deployment 
        uses: hasura/comment-progress@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'imperfect-fourth/test'
          number: ${{ github.event.number }}
          id: deploy-preview
          message: 'Deployment of a preview for this pull request was successful.'
          append: true 
